import Modal from './Modal';

export default function LegalModal({ type, onClose }) {
  if (!type) return null;

  return (
    <Modal show={!!type} onClose={onClose} className="legal-modal">
      <div className="legal-modal-header">
        <h2>{type === 'privacy' ? 'Privacy Policy' : 'Terms of Service'}</h2>
        <button className="legal-close-btn" onClick={onClose}>&times;</button>
      </div>
      <div className="legal-modal-body">
        {type === 'privacy' ? (
          <>
            <h3>Privacy Policy</h3>
            <p>Last updated: February 2026</p>
            <p>Lightspeed by Launchpad Solutions ("we", "us", "our") respects your privacy. This policy explains how we collect, use, and protect your personal information.</p>
            <h4>Information We Collect</h4>
            <ul>
              <li>Account information (name, email) via Google OAuth</li>
              <li>Organization data you provide</li>
              <li>Usage data (tool usage, API calls)</li>
              <li>Content you submit to our AI tools</li>
            </ul>
            <h4>How We Use Your Information</h4>
            <ul>
              <li>To provide and improve our services</li>
              <li>To manage your account and organization</li>
              <li>To communicate with you about our services</li>
            </ul>
            <h4>Data Security</h4>
            <p>We use industry-standard security measures to protect your data, including encryption in transit and at rest.</p>
            <h4>Contact Us</h4>
            <p>For privacy inquiries, contact us at hello@launchpadsolutions.ca</p>
          </>
        ) : (
          <>
            <h3>Terms of Service</h3>
            <p>Last updated: February 2026</p>
            <p>By using Lightspeed, you agree to these terms of service.</p>
            <h4>Service Description</h4>
            <p>Lightspeed is an AI-powered productivity suite for nonprofit organizations. We provide tools for content generation, data analysis, and team collaboration.</p>
            <h4>User Responsibilities</h4>
            <ul>
              <li>You are responsible for the accuracy of content you provide</li>
              <li>You must not use the service for unlawful purposes</li>
              <li>You are responsible for maintaining account security</li>
            </ul>
            <h4>AI-Generated Content</h4>
            <p>Content generated by our AI tools is provided as-is. You are responsible for reviewing and editing AI-generated content before use.</p>
            <h4>Contact Us</h4>
            <p>For questions about these terms, contact us at hello@launchpadsolutions.ca</p>
          </>
        )}
      </div>
    </Modal>
  );
}
